/**
 * Concatenates the eight pure rule-engine files into one ES module.
 *
 * Why concatenate instead of adding import/export to each file: the engine's
 * functions share one global scope and call each other across files in hundreds
 * of places. Rewriting them into modules risks silent breakage, and the engine
 * tests are the project's main safety net. Concatenating leaves every line of
 * game logic untouched, so those tests still guarantee it.
 */
import fs from 'node:fs';
import path from 'node:path';

const FILES = ['Config', 'RoleCatalog', 'Utils', 'Validation',
  'WinConditionService', 'EffectResolver', 'RuleEngine', 'GameService'];

const EXPORTS = [
  'APP_NAME','APP_VERSION','CAUSE','CAUSE_TH','EVENT_SOFT_LIMIT',
  'MAX_DEATH_QUEUE_ITERATIONS','ST','STATUS','TEAM','TEAM_TH','VILLAGE_IMPACT_VERIFIED',
  'addPlayer','addStatus','advanceStep','afterResolution','alivePlayers',
  'anyAliveWithRole','anyPlayerHadRole','applyCatalogOverrides','assertVersion',
  'assignRoles','assignmentStatus','attemptKill','buildNightSteps','catalogViewModel',
  'configureGame','createGameState','currentStep','deckRemaining','defaultRuleVariants',
  'detectedTeam','eligibleVoters','emit','endDayAndStartNight','endGame','enqueueDeath',
  'evaluateWin','finalSummary','findPlayer','findStep','finishNight','forceEndDay',
  'getRole','hasRoleDef','hasStatus','isCultMember','isThreatToSeer','isWolfTeam',
  'listRoles','livingNeighbours','moderatorKill','moderatorViewModel','mustPlayer',
  'neighboursForPI','openNomination','pauseGame','playersWithRole','processDeathQueue',
  'publicViewModel','removeStatus','reopenRoleAssignment','resolveDeathPrompt',
  'resolveNight','resolvePrompt','resolveVote','resumeGame','roleDisplay','seatOrder',
  'setPlayers','skipStep','startDiscussion','startGame','startNight','startNomination',
  'statusLabel','submitRoleAction','submitVote','tallyVotes','timeline',
  'uwClone','uwContains','uwEscape','uwGameId','uwNow','uwPin','uwPush','uwRandomId',
  'uwRemove','uwUnique','validateRoleSelection','validateTargets','validateVote',
  'villageImpactSummary','voteWeight','winTeamLabel'
];

/* Apps Script services must never reach the engine: the whole test strategy
 * depends on these files running in plain Node with nothing mocked. */
const BANNED = ['SpreadsheetApp', 'CacheService', 'PropertiesService', 'LockService'];

const ENGINE_DIR = path.join(process.cwd(), 'lib', 'engine');
const OUT = path.join(process.cwd(), 'lib', 'engine.generated.js');

const HEADER = `/* AUTO-GENERATED by scripts/build-engine.mjs — DO NOT EDIT.
 * แก้ที่ lib/engine/*.gs แล้วรัน npm run build:engine
 * ไฟล์นี้ห้าม commit (อยู่ใน .gitignore แล้ว) */\n\n`;

const declared = new Set();

const body = FILES.map(function (f) {
  const p = path.join(ENGINE_DIR, f + '.gs');
  const code = fs.readFileSync(p, 'utf8');
  for (const banned of BANNED) {
    if (code.indexOf(banned) >= 0) {
      throw new Error(f + '.gs เรียก ' + banned + ' — ไฟล์ตรรกะบริสุทธิ์ห้ามแตะ Apps Script API');
    }
  }
  const re = /^(?:function|var)\s+([A-Za-z_$][\w$]*)/gm;
  let m;
  while ((m = re.exec(code)) !== null) declared.add(m[1]);
  return '/* ===== ' + f + '.gs ===== */\n' + code;
}).join('\n\n');

/* A typo in EXPORTS would otherwise surface as a confusing runtime error inside
 * a route handler instead of here. */
const missing = EXPORTS.filter(function (n) { return !declared.has(n); });
if (missing.length) {
  throw new Error('EXPORTS อ้างชื่อที่ไม่มีใน lib/engine/: ' + missing.join(', '));
}

fs.writeFileSync(OUT, HEADER + body + '\n\nexport {\n  ' + EXPORTS.join(',\n  ') + '\n};\n');
console.log('สร้าง lib/engine.generated.js จาก ' + FILES.length + ' ไฟล์ / export ' + EXPORTS.length + ' รายการ');
